language: go

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.24.0

go:
  - master
  - "1.12"

install: true

matrix:
  allow_failures:
    - go: master
  fast_finish: true

notifications:
  email: true

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose up -d zero server

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
  - go get golang.org/x/lint/golint                             # Linter
  - go get honnef.co/go/tools/cmd/megacheck                     # Badass static analyzer/linter
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/go-playground/overalls

script:
  # Run all the tests with the race detector enabled
  - overalls -project=github.com/romshark/dgraph_graphql_go -covermode=atomic -debug -- -race -v -coverpkg=./...
  - $HOME/gopath/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken=$COVERALLS_TOKEN

  # go vet is the official Go static analyzer
  - go vet ./...

  # "go vet on steroids" + linter
  - megacheck ./...

  # one last linter
  - golint -set_exit_status $(go list ./...)

  # Build cmd/api
  - go build -o apisrv cmd/api

  # Run API tests
  - go test -v -race ./apitest/... -host "localhost:8090" -dbhost "localhost:10180"